[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/actuator/health"
healthcheckTimeout = 100
startCommand = "java -jar app.jar --spring.profiles.active=railway"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
