[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -jar app.jar --spring.profiles.active=railway"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
